import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import "bulma/css/bulma.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/job/create">Create Job</Link>&nbsp;&nbsp;&nbsp;&nbsp;
                <Link href="/login">Login</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="section">{children}</main>
      </body>
    </html>
  );
}
